---
title: "Response to Reviewers - Duraisamy et al., 2025,  IRCOBI"
format:
  pdf:
    toc: false
    number-sections: false
    colorlinks: false
    documentclass: scrartcl
    papersize: letter
---


## Reviewer 1



**This is a study of low-moment range of motion in male and female osteoligamentous cervical spine segments based  on previous testing in the NHTSA database performed. In general, both the intrinsic and size differences between  men and women are of substantial interest, but here, no attempt is made to differentiate size related 
differences through biomechanical scaling, and certain of the underlying assumptions are questionable and/or 
unspecified.**


### Methods

**1.  At some point, the anatomical differences between female and male segments must be mentioned. Anatomically, the females are likely to be smaller AND the female FSUs are higher in the c-cpine in this dataset. Both are going to tend to exacerbate size-related differences in response to low moments and to injury response.**

- We had already addressed these in the subsections "Limitations" and "Sex-dependent cervical spine biomechanics" in the Discussion, but we understand it better to elaborate further on this to give a clearer picture to the reader. We have now expanded more on this with additional references in the section "Sex-dependent cervical spine biomechanics" and added a comment on the cervical spine segments available in the dataset in the "Limitations". 


**2. “The hyperprior is given by …”. It’s unclear why the prior for a male/female comparison comes from a male study as opposed to just using an uninformed prior. Or something else. Please specify what part of [14] was used for the priors since it is experimental and computational. If the experiments from [14] are used, are these some of the same experiments reported in [12]? Please clarify.**

- Even though the priors come from a male study, the parameters were defined such that prior is a weakly informative prior. The purpose of a weakly informative prior was to center the prior distributions. We have now added an additional figure in the appendix to show this (Fig A3). If anything, a weakly informative prior in this case will lead to conservative results. With the lack of additional experimental sources and with the lack information in this source as indicated in our responses to #1 [TODO], we can safely assume that specification of the current prior does not affect the conclusion of the study. 
- Hyperprior specifies distribution for flexion and extension (not sex-specific priors)
- experimental data from appendix of [14] is used in this paper. This study consisted of only male samples. [12] contains only female samples and hence we can conclude that they are not the same experiments.
- We also checked if [13] and [14] contain the same experiments. The cervical spine levels used in the two studies are different and hence can be concluded that it is not the same samples. Also, the studies acknowledge different funders.

**3. Some of the distribution assumptions seem unnecessary if Bayesian nonparametric modelling is used.**

- We are using parametric linear regression (shown in equation 1) and we have assumed normal distributions for all the parameters.

**4. Generally, some scaling for size must be included in such a study since this is likely a strong predictor of low moment motion.**

- The initial plan for our study was to include anthropometric and morphological variables in the analysis. However, these are not recorded in the NHTSA database for these experiments. Height and weight data was found in pdf report for only one PMHS B03 (female). 
- All other papers published by Nightingale and Myers were checked to see if any related information could be extracted. Such information is available only for PMHS used for tension tests. PMHS id used in bending tests were different from tension tests, and hence are not the same samples.
- The study we used to define priors reported the anthropometry of the individuals from who the samples were tested. We have now made an exploratory data visualization to compare the rotations at 3Nm with respect to height, mass, and BMI. No relationships can be seen visually. 

### Results

**5. The Bayesian model specification should be in the methods.**

- Thank you, this is moved the methods

**6. “The posterior distribution was verified using various checks.” Please specify what this means. What checks, and what constituted verification in this case.**

- The lines that followed this statement was meant to direct the reader to the appendix for details about these verifications. We now describe this in some more detail to be clearer.
- R_hat and Effective Sample Size (ESS) was used to evaluate the sampling. We have not included this in the main text, along with the reference to the algorithm. `Vehtari, Aki, Andrew Gelman, Daniel Simpson, Bob Carpenter, and Paul-Christian Bürkner. "Rank-normalization, folding, and localization: An improved R ̂ for assessing convergence of MCMC (with discussion)." Bayesian analysis 16, no. 2 (2021): 667-718.`

**7. “for the group level-effect, extension and flexion responses for females are seen to be greater than males.” This is unclear. If it means that the extension and flexion angles for females to a given moment level are greater than males, with some anthropometric specifications), then this is likely generally true. However, some discussion of this would be nice here, including the likely observation that size differences play a role here.**

- This statement was meant to point to the posterior distributions of the coeefficients (Figure 1). We have updated this in the manuscript
- In general, the female segments can be expected to be more flexible. The purpose of this study was to quantify how different they and in the process we found that it is more different in flexion than extension (which is explained in the next paragraph in the manuscript)
- We agree size differences will play a role. Unfortunately as most of these studies do not report either anthropometry or local morphological dimensions, it is a challenge to do any quantification in the analysis. This relates to our response to question #1, and we have expanded on this in the manuscript in the discussion section.
- We have also provided visualization from the only study where we found anthropometric variables reported (Fig A10)


**8. One additional limitation is repeated testing on these specimens. At 3 Nm, this is likely not a primary effect, but should be mentioned.**

- Thank you. We agree it is important to give this context to the reader and we have now included this in the methods (line 50)

### Discussion

**9. “… male … has overlapping distributions … female … did not show … overlap”. Likely a part of this is the size differences and the moment angle relative to the overall range of motion in an osteoligamentous c-spine in flexion. The increase in extension moment happens nearer in angle to the nominal position than the flexion. One thing more difficult to understand is why the distributions do not widen in the flexion cases and seem approximately the same as in the extension case.**

- with the statement "the male flexion and extension has overlapping distributions, the female responses did not show similar overlap" we intended to describe the asymmetry we saw for flexion and extension in females. Males had a similar distribution for extension and flexion at 3Nm, but this was not the case for females.
- The distributions capture the variations between the samples and the uncertainty in the experiments at a moment loading of 3Nm. This may not necessarily need to be different between flexion and extension. In the male distributions (Fig 2), the distribution for flexion can be seen to be slightly wider than extension.


**10. “… could perhaps…” This is well known. In fact, it is quite difficult to injure the neck in pure flexion moment before facial structures contact the torso. In contrast, extension moments load the c-spine to failure at relatively small angles.**

- We agree, but we were trying to discuss here why female extension is similar to male extension, while female flexion is not similar to male flexion in physiological range-of-motion at subinjurious bending moment. We have now expanded on the description in this paragraph to better discuss this.

**11. “… may exhibit sex-dependent variations.” From a structural anthropometric point of view, males and females have size-dependent variations. Also, this is true within males and females. So, for such a low-moment study, it is essential to separate sex intrinsic variations and geometric variations. Specimen anthropometry is available for these tests. Using the gross anthropometry and segmental correlations of anthropometry and segmental length (and circumferences), some estimate of the size effect can be obtained.**

We agree. The initial intention of the study was to consider all influence of geometry variation and anthropometry variables. However, as described in our responses to **#4** we did not find this information neither in the NHTSA database or related publications. Even with the lack of these information, we want to highlight that the male and female segmental responses are different. Female are shorter than males, and consequently have a different anthropometry which needs to be considered in computational models.


### Appendix

**12. “… there were 48 female and 29 male FSUs…”. Please clarify these are tests, using 16 female and 16 male spine as in the studies. They are not independent spines.**

- Thanks. This was mentioned in the methods initially and we have added it to the Appendix also.


## Reviewer 2

This study quantifies sex differences in cervical neck kinematics using retrospective data from previously published experimental work.

**13. Introduction: what is the status of cervical neck biofidelity in current HBMs using the morphing techniques and/or limited experimental validation data? Are their biofidelity scores low with these approaches? Please expand on the practical effects for HBMs when sex is not considered in calibration/validation.**

- Currently the VIVA+ (morphs a female baseline to male) and GHBMC (morphs a male to female) are the two major HBMs that using morphing techniques. Both these models do not report sex-specific validation. The implications of not including sex-specific calibration/validation include not being able to study the sex-differences in injury pattern, especially for low-speed impacts where female tend to be at higher risk of whiplash associated disorders.
- We have now update the Discussion subsection "Considerations for Human Body Models" to address these questions.


**14.  Methods: It would be prudent to include some additional details for the retrospective data so that the reader does not have to search through refs 12 and 13 to understand if the boundary conditions were the same across the published data that were used:- did they change boundary conditions between tests/sex. It appears that different segmentation of the cervical vertebrae was used at the least.**



**15. Were the ages of the PMHS similar across sex? Were there any inclusion/exclusion criteria that may influence the findings of this current paper (especially any cervical degeneration that may influence response)?**

- For male age varies from 47 to 74 (61.13 avg), For female age varies from 33 to 58 (48.16 avg)
- The authors of the study did not mention any exclusion criteria in PMHS. Most of the causes of death were related to cardio.
    
**16.  Were data from all cervical segments referenced (C3-C4 and C5-C6 for females; C4-C5 and C6-C7 for males) combined in the Bayesian model? Are the degrees reported in the results an average across all segments? Your abstract states “segmental rotation” but you’re reporting only singular degree values when comparing males and females. Please clarify.**
  
- Yes, all the segments were combined together for the analysis. The segmental rotation reported at 3Nm is for all the segments.
- In the abstract, we wrote "the segmental rotation of C3-C7 cervical spine segments at a flexion and extension load of 3 Nm". 
 TODO
  - 

**17.  Please include the criteria or justification or rationale for your selection of “wider distributions” when defining the priors. How could this selection decision affect your results?**

- The wider distribution was used to serve as a weakly informative prior and serves to center the prior in the range of physiological rotation we expect the cervical spine segments to exhibit. We have now added an additional figure in the Appendix (A3) to show the result of the wider distributions on the prior predictive distribution before the model has been fitted with the data. 
- Early in the process of designing the study, we tested different priors including flatter prior and this did not see an influence on the results. However, part of the Bayesian workflow is to include "expert knowledge" as priors and hence we include the priors that convey the knowledge we have on cervical spine segmental rotation at 3Nm, that it would be greater than 0 degrees and that we do not expect it be more than 20 degrees. 


**18.  Results: The terms “rotation” and “flexion/extension” seem to be used interchangeably? I am confused by the use of segmental rotation in flexion and extension. What anatomical plane is segmental rotation being measured in? This again is likely discussed in the referenced papers but brief clarifications here and/or a figure demonstrating the results would help to interpret your analysis.**

- By flexion and extension, we refer to the loading direction. In spine segments, flexion is the forward motion about the sagittal plane, and extension is the backward motion. We use "rotation" because it is a response to a bending moment and it is measured as angle in degree.
- We have added (TODO)

**19.  Discussion: It is important, in your discussion of IV disc and ligaments exhibiting sex-specific variation to include some discussion/interpretation based on age (and the age distributions of the males vs. females included).**

- We agree this is important to consider. We have done additional analysis by adding age as a variable in the model and added it to the Appendix. For the dataset used in this study, we did not find an influence for age (Table AIV)

**20.  Your findings are asymmetry in flexion/extension response but also between sexes. Are current HBMs allowing for cervical flexion and extension kinematics to be equal? Please elaborate and discuss further the implications of your work presented here.**

  - Check validation reports from current HBMs. Connect to 13.
  - (PD) We didn't have any literature showing HBMs having same response on Extension and Flexion, But one thing we could say is THUMS didnt validate its cervical for this quasi static moment loading.
  - (PD) moreover in 13, 1st paper they spoke only about Flexion. The author mentioned that the FSU is very stiff (approx. 2 deg. at 3.5 Nm). As it cannot hit the spinous process at that angle, we could expect the same in Extension too. I couldn't find any other literatures from the authors.

**21.  Again, please clarify your use of the term “spinal rotations.” Are you using this interchangeably with flexion/extension movements?**

- Thanks for the comment. Please answer to #18 for detailed response. We have also ensured that this is clearly described in the paper. (TODO)

**22.  In the limitations, you mention that females may have smaller cervical vertebrae and intervertebral dimensions than males that could influence rotations; however, the anatomical features are conserved across sexes such that size would not influence relative movement of the cervical segments. Suggest re-thinking this assertion with an anatomical perspective.**

- Even though the anatomical features are conserved, due to the assymetry  of the structure, the rotation of the segments can be influenced. For example, in extension, the articular processes restrict the rotation regardless of size. However, in flexion, there is nothing stopping the rotation and the smaller female cervical spine segments will rotate more for the same applied moment. This is the only way to explain the current results and perhaps more studies using imaging techniques are required to understand this better. 
- We have added text in the section "Sex-dependent Cervical Spine Biomechanics" in the discussion to elaborate on this. 


